* AppPAL
** Policies
*** BYOD

- Translating policies for
  - SANS
  - NHS Torbay

**** TODO Which attributes described in SecPAL paper are needed to express BYOD policies?
**** TODO David to chase /Mobile Iron/.

*** Property checking

- Stop calling it Lint.
- Completeness is to be renamed /satisfiability/ or /derivability/.

**** TODO Survey XACML methods for property checking

** Knowledge Distribution

*** Modelling protocols in Pi-Calculus

What happens when you compose policies from different places which conflict?



*** TODO what policies are there that really need to be distributed?

*** What happens when time becomes a part of a policy?

** Uncertain Knowledge
   - Annotation on ~says~ part of SecPAL.
   - Quantified with respect to belief in any given statement.
   - How do you handle independence
  
*** TODO lit survey

** Tasks
*** TODO Find an expert to ask about policies
    - /Naranka Dulay/ at Imperial?
    - Michael Ravatsos at Edinburgh?
*** DONE [7/7] Read Papers added to Zotero
- [X] XACML 3.0 in Answer Set Programming. /Carroline Dewi Puspa Kencana Ramli, Hanne Riis Nielson, and Flemming Nielson./
- [X] The Logic of XACML. /Carroline Dewi Puspa Kencana Ramli, Hanne Riis Nielson, and Flemming Nielson./

Presents formalization of XACML, and derives a logic that represents it.
Very readable given the dryness of the subject.
    
- [X] Access Control via Belnap Logic: Intuitive, Expressive, and Analyzable Policy Composition. /Glenn Bruns, Michael Huth./
- [X] Access Control in an Open Distributed Environment. /R.J. Hayton, J.M. Bacon, K. Moody./

Seems to be an explanation of an early OASIS based system.
Not sure what's meant to be interesting about it.

- [X] Formalisation and Implementation of the XACML Access Control Mechanism. /Massimilano Masi, Roario Pugliese, Francesco Tiezzi./
- [X] Synthesising Verified Access Control Systems in XACML. /Nan Zhang, Mark Ryan, Dimitar P. Guelev./

They take a toy system called RW and show how it can be implemented in XACML.
Again, this seems like a pile of highly citable but not interesting poop.

- [X] Detecting Incompleteness, Conflicting and Unreachability XACML Policies using Answer Set Programming. /Carroline Dewi Puspa Kencana Ramli./

Really useful.   See work from <2016-04-20 Wed>.





** Other things
   - David to switch my funding from /Intel/ to /App Guarden/ from /April/ to /June/ for expenses reasons.x



